# Generated by Django 2.2.6 on 2019-10-24 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('StartDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField(null=True)),
                ('NotificationDate', models.DateTimeField(null=True)),
                ('IsGoal', models.BooleanField()),
                ('Frequency', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TimeRestriction',
            fields=[
                ('Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('StartDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField(null=True)),
                ('Frequency', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=50, unique=True)),
                ('Passwd', models.CharField(max_length=150)),
                ('Gender', models.CharField(max_length=15, null=True)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationTimeRestriction',
            fields=[
                ('Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('TimeRestrictionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.TimeRestriction')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.User')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationEvent',
            fields=[
                ('Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('EventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Event')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.User')),
            ],
        ),
    ]
